<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('field_price')->insert([
            [
                'field_price_id' => 1,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '06:00:00',
                'end_time' => '07:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 2,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '07:00:00',
                'end_time' => '08:00:00',
                'price' => 100000,
                'min_rental' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 3,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '08:00:00',
                'end_time' => '08:30:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 4,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '08:30:00',
                'end_time' => '09:00:00',
                'price' => 100000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 5,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '13:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 6,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'price' => 100000,
                'min_rental' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 7,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Monday',
                'start_time' => '15:00:00',
                'end_time' => '22:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 8,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Tuesday',
                'start_time' => '07:00:00',
                'end_time' => '10:30:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 9,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Tuesday',
                'start_time' => '10:30:00',
                'end_time' => '12:00:00',
                'price' => 70000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 10,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Tuesday',
                'start_time' => '12:00:00',
                'end_time' => '21:30:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 11,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Wednesday',
                'start_time' => '08:00:00',
                'end_time' => '22:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 12,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Thursday',
                'start_time' => '07:30:00',
                'end_time' => '21:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 13,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Friday',
                'start_time' => '06:30:00',
                'end_time' => '23:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 14,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Saturday',
                'start_time' => '07:00:00',
                'end_time' => '23:30:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'field_price_id' => 15,
                'field_id' => 'dcb38c24-adb0-4c57-9551-ed4413becf4o',
                'day_of_week' => 'Sunday',
                'start_time' => '08:00:00',
                'end_time' => '20:00:00',
                'price' => 200000,
                'min_rental' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
